//Authentication actions
export const SIGN_IN_SUCCESSFUL = 'SIGN_IN_SUCCESSFUL';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const SIGN_OUT = 'SIGN_OUT';
export const START_SIGN_IN = 'START_SIGN_IN';

//Manage accounts actions
export const START_FETCHING = 'START_FETCHING';
export const FETCH_STUDENT_SUCCESSFUL = 'FETCH_STUDENT_SUCCESSFUL';
export const FETCH_LECTURER_SUCCESSFUL = 'FETCH_LECTURER_SUCCESSFUL';
export const FETCH_FAILED = 'FETCH_FAILED';
export const UPDATE_STUDENT_PAGE = 'UPDATE_STUDENT_PAGE';
export const UPDATE_LECTURER_PAGE = 'UPDATE_LECTURER_PAGE';