/* AUTHENTICATION */
export const SIGN_IN_SUCCESSFUL = 'SIGN_IN_SUCCESSFUL';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const SIGN_OUT = 'SIGN_OUT';
export const START_SIGN_IN = 'START_SIGN_IN';
export const REMOVE_AUTH_ERROR = 'REMOVE_AUTH_ERROR';

/* ACCOUNTS */

//handle fetch accs
export const START_FETCHING_LECTURER_ACC = 'START_FETCHING_LECTURER_ACC';
export const START_FETCHING_STUDENT_ACC = 'START_FETCHING_STUDENT_ACC';
export const FETCH_STUDENT_SUCCESSFUL = 'FETCH_STUDENT_SUCCESSFUL';
export const FETCH_LECTURER_SUCCESSFUL = 'FETCH_LECTURER_SUCCESSFUL';
export const FETCH_STUDENT_FAILED = 'FETCH_STUDENT_FAILED';
export const FETCH_LECTURER_FAILED = 'FETCH_LECTURER_FAILED';

//remove error
export const REMOVE_STUDENT_ERROR = 'REMOVE_STUDENT_ERROR';
export const REMOVE_LECTURER_ERROR = 'REMOVE_LECTURER_ERROR';

/* SURVEYS */
//Surveys List
export const START_FETCHING_SURVEY = 'START_FETCHING_SURVEY';
export const FETCH_SURVEY_SUCCESSFUL = 'FETCH_SURVEY_SUCCESSFUL';
export const FETCH_SURVEY_FAILED = 'FETCH_SURVEY_FAILED';
export const REMOVE_SURVEY_ERROR = 'REMOVE_SURVEY_ERROR';

//Survey Version
export const START_FETCHING_SURVEY_VER = 'START_FETCHING_SURVEY_VER';
export const FETCH_SURVEY_VER_SUCCESSFUL = 'FETCH_SURVEY_VER_SUCCESSFUL';
export const FETCH_SURVEY_VER_FAILED = 'FETCH_SURVEY_VER_FAILED';
export const REMOVE_SURVEY_VER_ERROR = 'REMOVE_SURVEY_VER_ERROR';
