/* AUTHENTICATION */
export const SIGN_IN_SUCCESSFUL = 'SIGN_IN_SUCCESSFUL';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const SIGN_OUT = 'SIGN_OUT';
export const START_SIGN_IN = 'START_SIGN_IN';
export const REMOVE_AUTH_ERROR = 'REMOVE_AUTH_ERROR';

/* ACCOUNTS */

//handle fetch accs
export const START_FETCHING_LECTURER_ACC = 'START_FETCHING_LECTURER_ACC';
export const START_FETCHING_STUDENT_ACC = 'START_FETCHING_STUDENT_ACC';
export const FETCH_STUDENT_SUCCESSFUL = 'FETCH_STUDENT_SUCCESSFUL';
export const FETCH_LECTURER_SUCCESSFUL = 'FETCH_LECTURER_SUCCESSFUL';
export const FETCH_STUDENT_FAILED = 'FETCH_STUDENT_FAILED';
export const FETCH_LECTURER_FAILED = 'FETCH_LECTURER_FAILED';

//handle page change
export const UPDATE_STUDENT_PAGE = 'UPDATE_STUDENT_PAGE';
export const UPDATE_LECTURER_PAGE = 'UPDATE_LECTURER_PAGE';
//remove error
export const REMOVE_STUDENT_ERROR = 'REMOVE_STUDENT_ERROR';
export const REMOVE_LECTURER_ERROR = 'REMOVE_LECTURER_ERROR';

/* SURVEYS */
export const START_FETCHING_SURVEY = 'START_FETCHING_SURVEY';
export const FETCH_SURVEY_SUCCESSFUL = 'FETCH_SURVEY_SUCCESSFUL';
export const FETCH_SURVEY_FAILED = 'FETCH_SURVEY_FAILED';
export const UPDATE_SURVEY_PAGE = 'UPDATE_SURVEY_PAGE';
export const REMOVE_SURVEY_ERROR = 'REMOVE_SURVEY_ERROR';
